### ISSUE TITLE
add series name info to output files 

### ISSUE THREAD

**Issue by schavez6** [kdestasio/bidsQC#7]
would it be possible to add info in the bids conversion output files to reflect the series name of the files being copied over?  for example, if there are 3 functional runs, and only two make it into pretty bids format, the output might say "error: wrong number of files; largest file copied", but it would be nice to know the original name of the file too.

**Comment by kdestasio** [comment]
That output is generated by the dcm2bids scripts maintained by UNFmontreal. Here's their link if you'd like to open an issue there: https://github.com/UNFmontreal/Dcm2Bids
